# -*- coding: utf-8 -*-
"""Регрессия ДанкоT.C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVEMyAyHt1JYPEg2YTJRQ1tZH7NzQ4NG
"""

# импорт нужных библиотек
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing # подключаем датасет из sklearn
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import cross_val_score

from sklearn import metrics
from collections import Counter

# сразу напишем код функции, которая будет вычислять все нужные метрики

def Reg_Models_Evaluation_Metrics (model,X_train,y_train,X_test,y_test,y_pred):
    cv_score = cross_val_score(estimator = model, X = X_train, y = y_train, cv = 10)

    # Calculating Adjusted R-squared
    r2 = model.score(X_test, y_test)
    # Number of observations is the shape along axis 0
    n = X_test.shape[0]
    # Number of features (predictors, p) is the shape along axis 1
    p = X_test.shape[1]
    # Adjusted R-squared formula
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    RMSE = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
    R2 = model.score(X_test, y_test)
    CV_R2 = cv_score.mean()

    print(f'RMSE:  {round(RMSE,4)}\n  R2: {round(R2,4)}\n Adjusted R2: {round(adjusted_r2, 4)}\n Cross Validated R2: {round(cv_score.mean(),4)}')
    return R2, adjusted_r2, CV_R2, RMSE

df_housing = fetch_california_housing()

# смотрим описание датасета

print(df_housing['DESCR'])

# выведем названия фич
df_housing.feature_names

# нарисуем диаграммы рассеяния, чтобы лучше понять, как признаки (фичи) связаны с целевой переменной

for index, feature_name in enumerate(df_housing.feature_names):
    plt.figure(figsize=(5, 4))
    plt.scatter(df_housing.data[:, index], df_housing.target)
    plt.ylabel('median house value', size=12)
    plt.xlabel(feature_name, size=12)
    plt.show()

# загружаем данные в pandas dataframe
df = pd.DataFrame(data=df_housing.data,columns=df_housing.feature_names)
df["DP"] = df_housing.target
df

# подготавливаем датасет к обучению

X = df.drop(['DP'], axis=1)
y = df['DP']
print(f'X shape: {X.shape} | y shape: {y.shape} ')

# делим датасет на трейн и тест

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=15)




from sklearn.linear_model import LinearRegression

# Create a linear regression model
modelLR = LinearRegression()

# Fit the model to the data
modelLR.fit(X_train, y_train)

# Predict the response for a new data point
y_pr_LR = modelLR.predict(X_test)

_ = Reg_Models_Evaluation_Metrics(modelLR, X_train, y_train, X_test, y_test, y_pr_LR)

# попробуем отрисовать, как выглядит наша линейная регрессия

X2 = df['MedInc'].values[:,np.newaxis]
# target data is array of shape (n,)
y2 = df['DP'].values


model2 = LinearRegression()
model2.fit(X2, y2)

plt.scatter(X2, y2,color='g')
plt.plot(X2, model2.predict(X2),color='k')
plt.ylabel('median house value', size=12)
plt.xlabel('MedInc', size=12)
plt.show()



from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)

poly_features = poly.fit_transform(X)
X_p_train, X_p_test, y_p_train, y_p_test = train_test_split(poly_features, y, test_size=0.3, random_state=42)

# Create a linear regression model
modelPR = LinearRegression()

# Fit the model to the data
modelPR.fit(X_p_train, y_p_train)

# Predict the response for a new data point
y_pr_PR = modelPR.predict(X_p_test)

_ = Reg_Models_Evaluation_Metrics(modelPR, X_p_train, y_p_train, X_p_test, y_p_test, y_pr_PR)

X2 = df['MedInc'].values[:,np.newaxis]
# target data is array of shape (n,)
y2 = df['DP'].values

poly_features = poly.fit_transform(X2)

model2 = LinearRegression()
model2.fit(poly_features, y2)


plt.scatter(X2, y2,color='g')
plt.plot(X2, model2.predict(poly.fit_transform(X2)),color='k')
plt.ylabel('median house value', size=12)
plt.xlabel('MedInc', size=12)
plt.show()



from sklearn.tree import DecisionTreeRegressor

# Create a stepwise regression model
modelDT = DecisionTreeRegressor()

# Fit the model to the data
modelDT.fit(X_train, y_train)

# Predict the response for a new data point
y_dt_pred = modelDT.predict(X_test)

_ = Reg_Models_Evaluation_Metrics(modelDT, X_train, y_train, X_test, y_test, y_dt_pred)



from sklearn.ensemble import RandomForestRegressor

# Create a stepwise regression model
modelRF = RandomForestRegressor(n_estimators=50)

# Fit the model to the data
modelRF.fit(X_train, y_train)

# Predict the response for a new data point
y_rf_pred = modelRF.predict(X_test)


_ = Reg_Models_Evaluation_Metrics(modelRF, X_train, y_train, X_test, y_test, y_rf_pred)




#SVR
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # ← numpy array
X_test_scaled = scaler.transform(X_test)

modelSVR = SVR(kernel='linear', cache_size=1000)
modelSVR.fit(X_train_scaled, y_train)
y_svr_pred = modelSVR.predict(X_test_scaled)
_ = Reg_Models_Evaluation_Metrics(modelSVR, X_train_scaled, y_train, X_test_scaled, y_test, y_svr_pred)

# Визуализация — ИСПРАВЛЕНО!
plt.figure(figsize=(8, 6))
plt.scatter(X_train["MedInc"], y_train, color='darkorange', label='data', alpha=0.5)  # ← DataFrame по имени
plt.scatter(X_train["MedInc"], modelSVR.predict(X_train_scaled), color='cornflowerblue', label='prediction', alpha=0.5)
plt.xlabel('MedInc')
plt.ylabel('median house value')
plt.legend()
plt.title('SVR - Linear Kernel')
plt.show()




  #полиномиальная модель
modelSVR_poly = SVR(kernel='poly', cache_size=1000)
modelSVR_poly.fit(X_train_scaled, y_train)
y_svr_poly_pred = modelSVR_poly.predict(X_test_scaled)
_ = Reg_Models_Evaluation_Metrics(modelSVR_poly, X_train_scaled, y_train, X_test_scaled, y_test, y_svr_poly_pred)

# Визуализация — ИСПРАВЛЕНО!
plt.figure(figsize=(8, 6))
plt.scatter(X_train["MedInc"], y_train, color='darkorange', label='data', alpha=0.5)
plt.scatter(X_train["MedInc"], modelSVR_poly.predict(X_train_scaled), color='cornflowerblue', label='prediction', alpha=0.5)
plt.xlabel('MedInc')
plt.ylabel('median house value')
plt.legend()
plt.title('SVR - Polynomial Kernel')
plt.show()



# Create a support vector regression model. Ядро - радиальная базисная функция
modelSVR_rbf = SVR(kernel='rbf', cache_size=1000)
modelSVR_rbf.fit(X_train_scaled, y_train)
y_svr_rbf_pred = modelSVR_rbf.predict(X_test_scaled)
_ = Reg_Models_Evaluation_Metrics(modelSVR_rbf, X_train_scaled, y_train, X_test_scaled, y_test, y_svr_rbf_pred)

# Визуализация — ИСПРАВЛЕНО!
plt.figure(figsize=(8, 6))
plt.scatter(X_train["MedInc"], y_train, color='darkorange', label='data', alpha=0.5)
plt.scatter(X_train["MedInc"], modelSVR_rbf.predict(X_train_scaled), color='cornflowerblue', label='prediction', alpha=0.5)
plt.xlabel('MedInc')
plt.ylabel('median house value')
plt.legend()
plt.title('SVR - RBF Kernel')
plt.show()



from sklearn.linear_model import ElasticNet

modelEN = ElasticNet(alpha=0.1, l1_ratio=0.8)
modelEN.fit(X_train, y_train)
y_en_pred = modelEN.predict(X_test)
_ = Reg_Models_Evaluation_Metrics(modelEN, X_train, y_train, X_test, y_test, y_en_pred)

# Визуализация — ИСПРАВЛЕНО!
plt.figure(figsize=(8, 6))
plt.scatter(X_train["MedInc"], y_train, color='darkorange', label='data', alpha=0.5)
plt.scatter(X_train["MedInc"], modelEN.predict(X_train), color='cornflowerblue', label='prediction', alpha=0.5)
plt.xlabel('MedInc')
plt.ylabel('median house value')
plt.legend()
plt.title('Elastic Net')
plt.show()